#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# A utility to print the specific line number of a text file.
# Credit: Evan Hahn [https://codeberg.org/EvanHahn]

lineno="$1"; shift
sed -n "${lineno}p" -- "$@"
