#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# A utility to show the current date in ISO format and the time.
# Credit: Evan Hahn [https://codeberg.org/EvanHahn]

echo "[+] ISO8601 Date: $(date '+%Y-%m-%d')"
echo "[+]   Local Time: $(date +%T\ %Z)"
echo "[+]     UTC Time: $(date -u +%T\ UTC)"
