#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# A utility to do text-to-speech in the terminal.
# Credit: Evan Hahn [https://codeberg.org/EvanHahn]

if hash espeak-ng 2>/dev/null; then
	pandoc -f commonmark -t plain --wrap=preserve | \
		espeak-ng -s 130
else
	>&2 echo "[-] Error: Couldn't find any TTS program. If Linux install espeak-ng."
	exit 1
fi
